language: node_js
node_js:
  - "stable"
script:
  - npm install --global workbox-cli
  - workbox generateSW workbox-config.js
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: volodymyrkushnir.com-staging
    region: eu-central-1
    on:
      branch: develop
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: volodymyrkushnir.com-production
    region: eu-central-1
    on:
      branch: master